### ISSUE TITLE
Interest in more sophisticated vagrantfile?

### ISSUE THREAD

**Issue by danieldreier** [davidcollom/puppet-serf#13]
I recently put together a [puppet-serf demo](https://github.com/danieldreier/serf-demo). Any interest in me merging that into the Vagrantfile on puppet-serf? I don't want to do a bunch of work if you prefer a very simple vagrant setup to begin with.

**Comment by davidcollom** [comment]
Hi. This has been very much on my to-do list! The current vagrantfile was simply usedfor initial building of the module and ensure services and config compiled correctly.

I know that there's a few pr's for this project and I do intend to review and merge as soon as I've got some free time.

**Comment by danieldreier** [comment]
Awesome! I'll put together a PR based on my previous work.

**Comment by danieldreier** [comment]
PR #14 includes a new Vagrantfile setup based on my puppet-serf demo repo, and also includes the "advertise" parameter PR changes, so I closed PR #12 because PR #14 won't work without advertise.

**Comment by danieldreier** [comment]
Closing because PR #14 is merged.
