### ISSUE TITLE
need to specify rpc_addr when overiding bind

### ISSUE THREAD

**Issue by garethr** [davidcollom/puppet-serf#3]
If you specify a custom bind value, for instance `$::ipaddress_eth1` then the value for rpc_addr will remain with the default value of `$::ipaddress`. The README indicates otherwise.

**Comment by davidcollom** [comment]
Hi, thanks for your feedback. I've updated the readme to better reflect the actual behaviour.

I original wote the module, however I've never had the opportunity to use. I also aim to implement rspec tests in the future.
