### ISSUE TITLE
Option to use system packages instead of wget?

### ISSUE THREAD

**Issue by solarkennedy** [davidcollom/puppet-serf#5]
In larger installations, wgetting is not "web scale"

Would you accept a PR for parameters like:
install_source => (url / package )
package_name = 
package_ensure =

I can leave the default behavior to be url so the behavior doesn't change, but enable to option to use a package if desired?

**Comment by davidcollom** [comment]
Hi. I'd be happy with that to go ahead. As long as default is wget yea!

**Comment by solarkennedy** [comment]
Cool. I'll work on that after the version fix PR is complete so I can properly test it with 0.3.0.
